DomainNet_DATA_FOLDER = "/root/dataset/DomainNet"
OfficeHome_DATA_FOLDER = "/root/dataset/OfficeHome"
VLCS_DATA_FOLDER = "/root/dataset/VLCS"
PACS_DATA_FOLDER = "/root/dataset/Dataset/PACS"
TerraIncognita_DATA_FOLDER = "/your_dir/dataset/TerraIncognita"
Fundus_DATA_FOLDER = "/root/dataset/Fundus"
